name = "dom-directus-generator"
account_id = "af7a7443fe6614fe0638319e5943ce4b"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
main = ".svelte-kit/cloudflare/_worker.js"

[assets]
directory = ".svelte-kit/cloudflare"

[vars]
DIRECTUS_URL = "https://cm-marketing.directus.app"
